### ISSUE TITLE
What is the URL after starting the dev-server?

### ISSUE THREAD

**Issue by DerekLiang** [jaysoo/todomvc-redux-react-typescript#2]
I am following the instructions in the README.md, and run the following command:

npm run dev-server

There is no error message on the console.

Tried the URL (http://localhost:2992/) with no luck.

**Comment by jaysoo** [comment]
Hi @DerekLiang, the dev server is the webpack server that will handle asset bundling. You'll need to start the app server in dev mode. 

```
npm run start-dev
```

And then browse to http://localhost:8000

Hope that helps.

**Comment by DerekLiang** [comment]
when I ran 'npm run start-dev' I got the following output:

```
$ npm run start-dev

> todomvc-redux-react-ts@1.0.0 start-dev C:\project\todomvc-redux-react-typescript
> node server/development

module.js:339
    throw err;
    ^

Error: Cannot find module '../build/stats-dev.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at module.exports (C:\project\todomvc-redux-react-typescript\server\index.js:11:35)
    at Object.<anonymous> (C:\project\todomvc-redux-react-typescript\server\development.js:1:81)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-dev"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! todomvc-redux-react-ts@1.0.0 start-dev: `node server/development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the todomvc-redux-react-ts@1.0.0 start-dev script 'node server/development'.
npm ERR! This is most likely a problem with the todomvc-redux-react-ts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/development
npm ERR! You can get their info via:
npm ERR!     npm owner ls todomvc-redux-react-ts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\project\todomvc-redux-react-typescript\npm-debug.log

```

**Comment by jaysoo** [comment]
@DerekLiang Make sure you run `npm run dev-server` first, otherwise the stats.json file (generated by webpack) will not be available.

**Comment by DerekLiang** [comment]
The 'stats-dev.json' has 0 bytes and does not exist in the build folder. I am not sure how to fix that. @jaysoo do you have any advice?

```
$ npm run dev-server

> todomvc-redux-react-ts@1.0.0 dev-server C:\project\todomvc-redux-react-typescript
> node webpack/dev-server.js

Listening at localhost:2992
ts-loader: Using typescript@1.7.5 and C:\project\todomvc-redux-react-typescript\tsconfig.json
Hash: 0c39590bc39403315718
Version: webpack 1.12.10
Time: 6849ms
                                                         Asset     Size  Chunks             Chunk Names
                                                          0.js  1.63 MB       0  [emitted]  todos
C:\project\todomvc-redux-react-typescript\build\stats-dev.json  0 bytes          [emitted]
chunk    {0} 0.js (todos) 1.39 MB [rendered]
    [0] multi todos 52 bytes {0} [built]
    [1] (webpack)-dev-server/client?http://0.0.0.0:2992 2.48 kB {0} [built]
    [2] (webpack)/~/node-libs-browser/~/url/url.js 22.3 kB {0} [built]
    [3] (webpack)/~/node-libs-browser/~/url/~/punycode/punycode.js 14.6 kB {0} [built]
    [4] (webpack)/buildin/module.js 251 bytes {0} [built]
    [5] (webpack)/~/node-libs-browser/~/url/~/querystring/index.js 127 bytes {0} [built]
    [6] (webpack)/~/node-libs-browser/~/url/~/querystring/decode.js 2.4 kB {0} [built]
    [7] (webpack)/~/node-libs-browser/~/url/~/querystring/encode.js 2.09 kB {0} [built]
    [8] (webpack)-dev-server/~/sockjs-client/lib/entry.js 244 bytes {0} [built]
    [9] (webpack)-dev-server/~/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
...
```

**Comment by jaysoo** [comment]
@DerekLiang I realize that the newer webpack stats plugin does not output the JSON file when using dev server. I downgraded the version for now until I can update the tooling.

Try pulling from master and it should work now.

**Comment by DerekLiang** [comment]
it worked. @jaysoo  Thanks!

**Comment by jaysoo** [comment]
No prob :)
